mozillians/humans/urls.py

The "correct" URL should not have a trailing `/`. 
I say correct in quotation marks because it's actually not uber important but more the fact that all other projects don't use a trailing slash. See http://contribute.paas.allizom.org/examples
Also, if we add a button to the FirefoxDeveloperEdition that checks for a `/contribute.json` presence then we might cause an unnecessary redirect. 
PS. I did not run the tests for this patch. I don't have the project set up other than a git fork.

correct contribute.json URL

---

mozillians/phonebook/tests/test_views/test_views_delete.py
mozillians/users/models.py

* When a Mozillian who should be autovouched deletes his profile, a race
condition happens between delete() and auto_vouch()
* Add flag to avoid triggering auto_vouch() on vouch flag update.

[Fix bug 1128729] Avoid race condition on profile delete.

---

mozillians/static/mozillians/css/main.less

Currenly textareas have a lighten border color. (See Bio at [edit profile](https://mozillians.org/en-US/user/edit/) for example). This is caused because we overwrite sandstone's default.

Use consistent border-color for both inputs and textareas

---

README.md
docs/api/api.rst
docs/contribute.rst
mozillians/humans/templates/humans/contribute.json
mozillians/templates/500.html
mozillians/templates/base.html

The component name changed from Community Tools to Participation Infrastructure.
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1134866

[fix bug 1134866] Update Bugzilla links

---

mozillians/settings/base.py

This fixes issues in local/dev/stage mozillians.org environments.

[Fix bug 1170046] Update example mapbox API token.

---

mozillians/groups/forms.py
mozillians/groups/models.py
mozillians/groups/tests/test_forms.py

We used duplicate code in groups/{forms,models}.py because of this:
https://code.djangoproject.com/ticket/16986
Now with Django 1.7 model can clean individual fields and there is
no need to clean both `ModelForm` and `Model`.

[Bug 1196244] Remove duplicate legacy code.

---

mozillians/urls.py

* https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#discovery-of-admin-files

[bug 1196244] Remove admin.autodiscover from url conf.

---

docs/api/apiv2/api-groups.rst
docs/api/apiv2/api-users.rst

The paramter values `true` and `false` don't work, however `True` and `False` work.

Fix API v2 boolean parameter value documentation.

---

mozillians/common/authbackend.py

* Introduced in django-browserid upgrade from v0.10.1 to v1
* Different definition of `def login_failure()`

Fix login_failure regression

---

Dockerfile
requirements/prod.txt

* We have a hard dependency of celery v2
* The required kombu version needs some deprecated code from python 2.7.10

Pin to python 2.7.10 and kombu 2.2.0

---

docs/installation/installation-docker.rst

A tiny fix on documentation. syncdb is deprecated on latest versions of Django.

Use migrate instead of syncdb

---

mozillians/groups/tests/test_views/test_misc.py
mozillians/groups/views.py

* Group with existing curators must have those as initial
* Group without curators should have request.user as initial
* On ``admins`` or ``managers`` edits lets keep curators intact.

Fix initial profiles in curator form.

---

mozillians/phonebook/views.py

* Instead of using CACHE backend to cache response in the
view level, add `cache-control` headers.

[bug 1254981] Replace cache_page with cache_control.

---

mozillians/groups/forms.py
mozillians/jinja2/groups/index_groups.html
mozillians/static/mozillians/js/group_index.js

* Use Meta.labels instead of manually patching __init__
* Fix l10n issue

Render `create group` errors on form submission.

---

mozillians/groups/admin.py

@comzeradd quick r?
I removed this for two reasons.
1) All the superusers are able to edit this through mozillians.org so it doesn't  really make sense to have this as readonly in admin.
2) It's easier to edit this through admin, especially during dev.

Remove the readonly field in Invites admin.

---

Dockerfile

* `apt-get update` gets cached and in case it fails the whole build
fails
* It's best practice to run all `apt` related commands to a single RUN

Fix docker build issues.

---

mozillians/jinja2/phonebook/about.html

Should be safe to default to HTTPS (and avoids an extra HTTP redirect).

Use HTTPS scheme for privacy URL

---

mozillians/jinja2/phonebook/profile.html

This hardcoded HTTP URL and another (the privacy_policy_url in https://github.com/mozilla/mozillians/blob/1ebc088c297a245bd8b156b0e4a3617f38c99c8b/mozillians/jinja2/phonebook/about.html#L37-L38) are coming up in another bug as a small issue (can catch you up, offline).  Should be a safe change.
r? @akatsoulas @johngian

Use HTTPS scheme for contribute URL

---

mozillians/settings/base.py

Sets the following HTTP headers:
- X-XSS-Protection: 1; mode=block
- X-Content-Type-Options: nosniff

[Fix bug 1275551] Enable django security middleware.

---

mozillians/phonebook/management/commands/check_basket.py
mozillians/phonebook/tests/test_check_basket.py
mozillians/phonebook/tests/test_views/test_views_delete.py
mozillians/settings/base.py
mozillians/users/admin.py
mozillians/users/models.py
mozillians/users/tasks.py
mozillians/users/tests/test_models.py
mozillians/users/tests/test_tasks.py

* Extend tasks to take `newsletters` as arg
* Add new `settings` entry for NDA basket
* When user changes email re-subscribe to all newsletters not only vouched

Refactor basket tasks to take `newsletters` as input

---

mozillians/settings/base.py
mozillians/users/admin.py

* Make current basket admin actions newsletter agnostic
* [Fix bug 1282445] Mass delete subscription functionality on admin
* [Fix bug 1282446] Mass run of subscriptions from /admin/

Refactor mass basket subscribe/unsubscribe admin actions

---

mozillians/common/middleware.py
mozillians/jinja2/includes/canonical_url.html
mozillians/jinja2/includes/lang_switcher.html
mozillians/settings/base.py

* Exclude /api and /admin URLs from L10N middleware.
* Fix LANGUAGES definition format.
* Use regex for URLs that are not to be localized.

Multiple L10N fixes

---

mozillians/jinja2/phonebook/home.html

As discussed, changing the 'Get Involved' CTA on front page to point to Activate, which is higher priority at the moment compared to the /contribute/ page.

Update 'Get Involved' CTA to link Activate

---

docker-compose.yml

We have a migration ``product_details.0002_auto_20151006_1348`` that makes ``'MySQL server has gone away'`` while running migration in docker environment.
I think, this patch should fix the issue.
I have tested on my local machine, and its working fine
@akatsoulas @johngian r?

Fixing docker environment for mysql database

---

docs/installation/installation-docker.rst

Was trying to get a docker instance up and running, and followed the docker installation instructions.  However, mozillians requires you to update the superuser profile you create in order to start using the app.  To do this, you need the country/region/city data loaded in the DB or it won't allow the user to advance through.  This update to the document is an attempt to make it so that others don't get hung up on this.

Add cities_light loading to docker installation instructions

---

mozillians/settings.py

* Use INFO level for `root` logger
* Use WARNING for `sentry.errors` and `raven`

Improve logging config.

---

mozillians/settings.py

* Add the verification client urls to OIDC_EXEMPT_URLS.

Enable OIDC refresh middleware to support federated logout.

---

mozillians/static/mozillians/css/main.less

Closing a sub-tree must not close all following direct siblings.
Resolves #2269.

Fix orgchart expansion bug.

---

mozillians/static/mozillians/css/main.less

This PR fixes a minor bug caused by the width of the form being different `from` the width of the `select` in the footer.

Fixes misaligned language select input

---

bin/run-celery.sh

Reverts mozilla/mozillians#2370
Now that the release is out we can test this properly without interfering with the rest of the Celery pipeline

Readd Disable prefetch for the CIS queue.

---

mozillians/jinja2/phonebook/profile.html

This potentially fixes empty GitHub logos.

Don't show an empty GitHub logo.

---

mozillians/common/tests/test_authbackend.py
mozillians/users/models.py
mozillians/users/tests/test_models.py

* Return privacy aware IDP when accessing profile.email
* Change UserProfile.privacy_email when saving primary identity

Support privacy aware access to IDP emails.

---

mozillians/settings.py

I have localized the site to [Canadian English (en-CA)](https://github.com/mozilla-l10n/mozillians-l10n/tree/master/en_CA). Please activate the new locale. Thanks!

Activate en-CA locale

---

mozillians/settings.py

I would like to merge my work from iam-infra-migration (https://github.com/mozilla/mozillians/pull/2850) into the dino-park branch. Once this is added, we can close the other PR and I can use CodeBuild to build and deploy the container image to ECR / update the Kubernetes deployment from changes on this branch.

adding S3 media storage backend support

---

k8s/templates/configmap.yml

Hey,
This is currently resulting in failed deployments in Kubernetes (dinopark-dev namespace). Once this is merged, I can trigger a build to update the running pods.

removes hard-coded namespace in configmap
