mozilla/mozillians

.gitmodules
mozillians/phonebook/forms.py
mozillians/phonebook/tests/__init__.py
mozillians/phonebook/tests/test_views/test_views_misc.py
mozillians/phonebook/validators.py
mozillians/settings/base.py
mozillians/urls.py
scripts/update/update.py
vendor-local/vendor.pth

* Upgrade Django to 1.6.10
* Upgrade django-compressor to v.1.4
* Remove django-jingo-offline-compressor dependency (not supported by latest django-compressor)
* Use django-compressor for offline compression

Upgrade to latest playdoh-lib

---

mozillians/templates/phonebook/profile.html

* Revert email field on profile page template
* Reverts part of commit e0802b482f7da442edcc3da46aada545d1a8d1cd

Fix failing UI tests on profile page.

---

mozillians/templates/phonebook/apikeys.html

Added fieldsets around form inputs and button to have consistent UI with other forms (eg. profile edit).

Use consistent UI for apikeys form

---

mozillians/users/api/v2.py
mozillians/users/tests/test_api_v2.py

* Add WEBSITE external account field.

[Fix bug 926673] Use privacy aware attributes instead of queries.

---

mozillians/groups/api/v2.py
mozillians/users/api/v2.py
mozillians/users/tests/test_api_v2.py

* Language
* Account
* Group
* Skill

Add missing API v2 filters

---

docs/api/api.rst
docs/api/apiv1/api-groups.rst
docs/api/apiv1/api-skills.rst
docs/api/apiv1/api-users.rst
docs/api/apiv1/index.rst
docs/api/apiv2/api-groups.rst
docs/api/apiv2/api-skills.rst
docs/api/apiv2/api-users.rst
docs/api/apiv2/index.rst

* Move API v1 to a seperate namespace
* Add docs for API v2

Update docs to provide information for API v2

---

mozillians/phonebook/forms.py

[fix bug 1155623] Change error message in skills validation.

---

mozillians/static/mozillians/css/main.less
mozillians/templates/phonebook/home.html

I got the search bar to move to the top on mobile, but I was not sure how to align the search bar on desktop view so that it looks the same way it did before.
@comzeradd

[fix bug 1133122] Move search bar to top on mobile

---

scripts/update/update.py

[bug 1196244] Remove 'fake' option from Django 1.7 migrations.

---

mozillians/templates/admin/base_site.html

[bug 1129848] Fix missing jquery library in admin.

---

mozillians/groups/admin.py

[fix bug 1198258] Fix 500 error when adding new group in admin.

---

mozillians/geo/lookup.py
mozillians/geo/tests/test_lookup.py

* Check if duplicate region/country exists
* Deduplicate region/country and their references if required
* Workaround similar to https://github.com/mozilla/mozillians/pull/1178

[Fix bug 1214010] Fix DB constraint violations for region, country.

---

mozillians/groups/migrations/0004_auto_20151028_0632.py
mozillians/groups/models.py

* Changed description to 1024 chars.
* Changed new_member_criteria to 1024 chars.

[fix bug 1218776] Change the max length in groups models.

---

mozillians/static/mozillians/css/main.less
mozillians/templates/phonebook/includes/photo_form.html
mozillians/templates/phonebook/includes/profile_edit_accounts.html
mozillians/templates/phonebook/includes/profile_edit_basic.html
mozillians/templates/phonebook/includes/profile_edit_location.html
mozillians/templates/phonebook/includes/profile_edit_registration.html
mozillians/templates/phonebook/includes/profile_edit_you.html

* Username now has a privacy selector fixed to Public
* Registration: Photo controls beneath the photo
* Location texts closer to their labels and aligned with them

UI profile edit fixes

---

mozillians/groups/migrations/0005_remove_groupmembership_invalidate.py
mozillians/groups/models.py

* `invalidate` flag is not useful any more
* We are going to use `terms_accepted` and `status` combination

[Fix bug 1207956] Remove `invalidate` flag.

---

mozillians/users/migrations/0003_auto_20151124_0647.py
mozillians/users/models.py
mozillians/users/tests/test_models.py

@johngian or @glogiotatidis r?

Vouch mozilla addresses

---

mozillians/phonebook/views.py

[bug 1228958] Change wording in registration message.

---

mozillians/static/mozillians/js/profile_edit.js

* Fixes chrome rendering issue

[Bug 1129848] Fix missing variable definition.

---

mozillians/static/mozillians/css/main.less
mozillians/templates/phonebook/includes/profile_edit_accounts.html

* Move privacy controls on the left
* Add delete icon

[Bug 1129848] Minor UI fixes on External Accounts settings

---

mozillians/users/models.py

Re-opening pull request #1286. My branch was checked out from the master branch, so it shouldn't need re-basing. I thought the PRs should be sent to the [next branch](https://github.com/mozilla/mozillians/tree/next) for review before it could be pushed to master.

[Fix 1232978] Removed extra trailing slash (/) to fix Telegram URLs

---

scripts/update/update.py

Reverts mozilla/mozillians#1294

Revert "[Fix bug 1242596] Change command order in update script."

---

mozillians/static/mozillians/css/main.less

fix this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1245807

[fix bug 1245807] fit image size

---

requirements/prod.txt

Add cffi and bcrypt to dev requirements.

---

mozillians/announcements/models.py
mozillians/common/authbackend.py
mozillians/common/helpers.py
mozillians/funfacts/models.py
mozillians/groups/admin.py
mozillians/groups/forms.py
mozillians/groups/models.py
mozillians/groups/tasks.py
mozillians/groups/views.py
mozillians/users/cron.py
mozillians/users/models.py
mozillians/users/tasks.py

Now with the 99 chars per line a few line breaks can be removed/restructured in favor of code readability. This is a step towards that direction.

Small pep8 beautifications.

---

mozillians/static/mozillians/js/profile_edit.js

[fix bug 1241606] Expand settings menu in mobile view.

---

docker-compose.yml
mozillians/settings/local.py-docker-dist

* Run celery worker instead of running tasks locally
* Run rabbitmq as a broker for celery tasks

Use rabbitmq and celery in docker development environment.

---

mozillians/groups/forms.py
mozillians/groups/tests/test_forms.py
mozillians/groups/views.py

* Fix initial data in curator form.
* When legacy group, initial should be empty.

[Fix bug 1248893] Don't force new curators in legacy groups edit.

---

mozillians/groups/tests/test_views/test_list.py

Explicitly define group names in tests.

---

mozillians/groups/views.py

[bug 1208367] Raise validation error if skill already exists.

---

mozillians/static/mozillians/js/group-edit.js
mozillians/templates/groups/add_edit.html

[fix bug 1230329] Toggle terms in groups edit.

---

mozillians/static/mozillians/css/main.less

Set the max size in multiple curators choicefield.

---

mozillians/static/mozillians/css/main.less

[Bug 1208367] Fix multiple selection dropdown width

---

mozillians/groups/views.py

[bug 1208367] Make search string lowercase.

---

mozillians/users/admin.py

* Raise error for the rest of the exceptions not handled in try/except

Don't catch all the exception on celery check.

---

scripts/update/update.py

Reverts mozilla/mozillians#1353

Revert "Drop and recreate djcelery table."

---

mozillians/groups/admin.py
mozillians/groups/migrations/0011_auto_20160307_0358.py
mozillians/groups/models.py

* Expose groups.Invite in /admin
* Add migrations for groups.Invite model

[Fix bug 1247221] Implement model backend for group invites.

---

requirements/prod.txt

[bug 1243710] Install rJSmin to requirements.

---

mozillians/groups/views.py

[bug 1258449] Add the creator of the group as member.

---

mozillians/jinja2/groups/includes/group_edit_access.html
mozillians/jinja2/groups/includes/group_edit_invitation.html
mozillians/jinja2/groups/index_groups.html
mozillians/static/mozillians/css/main.less
mozillians/static/mozillians/js/group_edit.js

* Minimize space on create group modal
* Use even space on no pending invitations text
* Minimize space on group types descriptions
* Add markdown informative text on terms
* Fix group access criteria toggle

[Fix bug 1247219] UI fixes for new group settings

---

mozillians/jinja2/phonebook/edit_profile.html

Fix indentation in edit_profile.

---

mozillians/groups/forms.py

[bug 1247221] Remove initial data from invites autocomplete form.

---

mozillians/groups/views.py
mozillians/jinja2/groups/edit_group.html
mozillians/jinja2/groups/includes/group_edit_invitation.html

Various group edit fixes

---

mozillians/groups/models.py
mozillians/groups/tests/test_views/test_show.py

[fix bug 1259071] Delete group invite when a user is removed from group.

---

mozillians/jinja2/groups/edit_group.html
mozillians/jinja2/groups/group.html
mozillians/jinja2/groups/includes/group_edit_access.html
mozillians/jinja2/groups/includes/group_edit_admin.html
mozillians/jinja2/groups/includes/group_edit_description.html
mozillians/jinja2/groups/includes/group_edit_invitation.html
mozillians/static/mozillians/css/main.less
mozillians/static/mozillians/js/group_edit.js

This would make the selection of Group settings tabs easier, especially for the selenium tests. It also add consistency with the Profile settings.

Add selectors on Group settings and info

---

mozillians/groups/admin.py
mozillians/groups/forms.py
mozillians/groups/migrations/0014_group_invite_email_text.py
mozillians/groups/models.py
mozillians/groups/tasks.py
mozillians/groups/tests/test_forms.py
mozillians/jinja2/groups/email/invite_email.txt
mozillians/jinja2/groups/includes/group_edit_invitation.html
mozillians/static/mozillians/css/main.less
mozillians/static/mozillians/js/group_edit.js

[fix bug 1259068] Add custom text in group invitation email.

---

mozillians/groups/views.py

[fix bug 1258324] Allow all mozillians to accept/reject invitations.

---

mozillians/jinja2/groups/includes/group_edit_access.html

[bug 1247219] Minor ui fixes.

---

mozillians/jinja2/groups/includes/group_edit_access.html
mozillians/jinja2/groups/includes/group_edit_invitation.html
mozillians/static/mozillians/css/main.less

* Fix Group title overflow text
* Limit select boxes width on mobile
* Proper arrangement of checkbox labels

[Bug 1247219] Fix Group settings UI elements

---

mozillians/groups/tasks.py
mozillians/groups/tests/test_tasks.py

[fix bug 1262079] Fix unicode error in group tasks.

---

requirements/dev.txt

@johngian quick r? This is needed for `fake-factory`.

Add missing dependency in dev.txt.

---

.travis.yml

Use specific python version for travis.

---

mozillians/groups/admin.py

Allow searching groups by curator in the admin interface.

---

mozillians/settings/base.py
mozillians/settings/local.py-devdist
mozillians/settings/local.py-docker-dist
mozillians/users/tests/test_tasks.py

* Cleanup stale references to BASKET_NEWSLETTER.

[Fix bug 1286524] Fix BASKET_NDA_NEWSLETTER config entry.

---

mozillians/users/tasks.py
mozillians/users/tests/test_tasks.py

* Check first for email changes
* Subscribe to required newsletters
* Update token if no token stored for mozillian yet

[Fix bug 1286559] Fix update basket subscriptions task.

---

mozillians/users/admin.py
mozillians/users/migrations/0008_userprofile_is_spam.py
mozillians/users/models.py

* Expose spam bit in /admin
* Allow filtering based on `is_spam` value

[Fix bug 1289117] Add entry in UserProfile to tag profile as spam.

---

docker-compose.yml

Create database with collation utf8.

---

docs/installation/installation-docker.rst

The link associated with docker-compose was throwing 404 error when opening. Updating the link.

[fix Bug 1303524] Update installation-docker.rst

---

mozillians/common/compress.py
mozillians/settings/base.py
mozillians/templates/compressor/css_file.html
mozillians/templates/compressor/css_inline.html
mozillians/templates/compressor/js_file.html
mozillians/templates/compressor/js_inline.html

* Implement custom css/js processor with sri support.
* Override compressor templates to support sri.
* Add settings to use custom js/css compressors

Implement SRI mixin for django-compressor

---

mozillians/settings/base.py
requirements/prod.txt

* Add middleware to delegate id_tokens

Bump OIDC lib version.

---

mozillians/settings/base.py

* Remove duplicate csp directives.

Deprecate `FRAME_SRC` directive.

---

mozillians/groups/models.py
mozillians/groups/tasks.py
mozillians/groups/tests/test_membership.py
mozillians/groups/tests/test_tasks.py
mozillians/groups/tests/test_views/test_show.py
mozillians/groups/urls.py
mozillians/groups/views.py
mozillians/jinja2/groups/email/membership_status_changed.txt

* PEP8 fixes.
* Improve code readability.
* Refactor notification system for membership changes.

[fix bug 1331590] Change membership to pending for non open groups.

---

mozillians/jinja2/phonebook/includes/profile_edit_developer.html
mozillians/jinja2/phonebook/includes/profile_edit_location.html

[bug 920376] Enable localization for the API template

---

mozillians/groups/forms.py
mozillians/groups/migrations/0015_groupmembership_needs_renewal.py
mozillians/groups/models.py
mozillians/groups/tasks.py
mozillians/groups/views.py

* minor changes to help readabiity.

Flag profiles ready to expire eligible for an early renewal.

---

mozillians/groups/views.py

[fix bug 1341608] Display all users regardless of memberhsip status.

---

mozillians/groups/tests/test_views/test_search.py
mozillians/groups/urls.py
mozillians/groups/views.py
mozillians/jinja2/phonebook/includes/profile_edit_basic.html
mozillians/phonebook/forms.py
mozillians/phonebook/tests/test_forms.py
mozillians/static/mozillians/js/profile_edit.js
requirements/prod.txt

* Refactor skills code.
* Minor PEP8 fixes.

Update to autocomplete v3.2

---

mozillians/groups/migrations/0017_auto_20170322_0710.py
mozillians/groups/models.py
mozillians/groups/views.py

* Raise the length of the name to 100 chars.
* Do not create a skill if already exists.

Fix tracebacks in autocomplete.

---

mozillians/users/models.py

Reverts mozilla/mozillians#1684

Revert "Log autovouching flow on sentry."

---

mozillians/groups/admin.py

* Remove old geolocation search fields from admin.

Enhance group membership admin filters.

---

mozillians/jinja2/base.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1333742

 [fix bug 1333742] Change Sign In button wording to include registration

---

mozillians/jinja2/groups/group.html
mozillians/jinja2/includes/search_result.html
mozillians/jinja2/phonebook/search.html
mozillians/static/mozillians/css/main.less

* Use same UI for both profiles and groups

Search UI Refactor

---

mozillians/jinja2/search/indexes/users/userprofile_text.txt
mozillians/phonebook/forms.py
mozillians/users/search_indexes.py

* Search in languages.
* Search in skills.
* Search in groups.
* Search in countries.
* Search in cities.
* Search in regions.

Enable search in related fields in userprofiles.

---

mozillians/jinja2/phonebook/search.html

Don't show advanced options to anonymous users.

---

mozillians/jinja2/phonebook/search.html

Reverts mozilla/mozillians#1758

Revert "Localize search template."

---

mozillians/static/mozillians/css/main.less

Ref: https://github.com/mozilla/parsys/issues/168

Fix long group names on search

---

mozillians/jinja2/base.html

Reverts mozilla/mozillians#1757

Revert "Infrastructure migration banner."

---

mozillians/users/admin.py

* Link to UserProfile on site
* Show profile date joined/last updated
* Filter based on skills

Enhance filtering of AbuseReport entries in /admin

---

mozillians/common/tasks.py
mozillians/settings/base_env_vars.py

* Notify healtchecks.io periodically to make sure that celery/celerybeat is up
and running

Improve celery monitoring.

---

mozillians/settings/base_env_vars.py

Update static_url path.

---

README.md

Hello Mozillians, :smiley:
I edit the `README.md` file. :pencil:
*Yours,*
[**Suriyaa**](https://mozillians.org/de/u/suriyaakudo/) 🦊 
(*PS: Is somebody interested to vouch me at https://mozillians.org/de/u/suriyaakudo/?*)

Use HTTPS protocol

---

mozillians/env-dist
mozillians/settings.py

* Remove duplicate configuration setting.

Add an env var for axes reverse proxy.

---

mozillians/common/authbackend.py
mozillians/common/tests/test_authbackend.py

* Drop the addition of emails in the ExternaAccounts.
* Fix the unique_together bug.
* Pass claims in the authenticate method.

Refactor authbackend.

---

README.md

**this PR does basically aim at:**
- *styling/docs (README.md file) - fixing typos; adding ToC*
---
**the motivation for such does basically lie within:**
- *improving accessibility of the file*;
- *making the file easier to be read*;
---
**with that i do basically aim at:**
- *encouraging users to come back to the file and contributing to it*

styling/docs (README.md file) - fixing typos; adding ToC

---

mozillians/users/api/v2.py
mozillians/users/tests/test_api_v2.py

Reverts mozilla/mozillians#1917

Revert "Update API to expose/filter IdpProfiles instead of ExternalAccounts."

---

mozillians/jinja2/base.html

Reverts mozilla/mozillians#1938

Revert "Banner - IAM changes"

---

mozillians/groups/forms.py
mozillians/groups/migrations/0019_auto_20171205_0544.py
mozillians/groups/models.py
mozillians/groups/tests/test_forms.py
mozillians/groups/views.py
mozillians/jinja2/groups/includes/group_edit_access.html
mozillians/jinja2/groups/index_groups.html
mozillians/static/mozillians/css/main.less
mozillians/users/models.py
mozillians/users/tests/test_models.py

* Allow employees with LDAP Identity Profiles to provision access groups.

Expose access groups in the UI.

---

mozillians/funfacts/migrations/0002_auto_20180103_0608.py
mozillians/funfacts/models.py
mozillians/funfacts/tests/test_models.py
mozillians/jinja2/phonebook/home.html

* Make the number field in the DB non required.

Enable markdown in funfacts.

---

docker-compose.yml
docker/files/mariadb.cnf
mozillians/env-dist

* Update the env-dist to include the ES host.
* Add a conf file for MariaDB.

Use a volume for DB storage.

---

mozillians/jinja2/phonebook/home.html
mozillians/jinja2/phonebook/profile.html
mozillians/phonebook/views.py
mozillians/users/models.py
mozillians/users/tests/test_models.py

* Display the inviter to users that can create access groups.

Split access groups and tags.

---

mozillians/celery.py

Reverts mozilla/mozillians#2063

Revert "Force INFO loglevel for sentry/celery integration."

---

mozillians/celery.py

Celery beat wasn't picking up the beat schedule using signals.
Switching back to ``app.conf.beat_schedule``.

Change celery beat schedule definition.

---

mozillians/common/middleware.py

* Fixes the random locales in EXEMPT_URLS.

Call get_response after handling the locale in the request.

---

mozillians/users/admin.py
mozillians/users/admin_forms.py

* Move admin forms in a separate file.

Add a button to send individual profiles to CIS.

---

mozillians/settings.py

* Add verification client in OIDC_EXEMPT_URLS

Enable refreshIDToken middleware.

---

mozillians/settings.py

Reverts mozilla/mozillians#2193

Revert "Enable refreshIDToken middleware."

---

bin/run-celery.sh

Relevant documentation:
http://docs.celeryproject.org/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings

Disable prefetch for the CIS queue.

---

bin/run-celery.sh

Reverts mozilla/mozillians#2342

Revert "Disable prefetch for the CIS queue."

---

mozillians/phonebook/views.py

Reverts mozilla/mozillians#2176

Revert "Do not swap accounts when comparing IDPs with equal priority."

---

mozillians/settings.py
requirements/prod.txt

* Upgrade mozilla_django_oidc to version 1.1.1

Enable signup flow in NLX.

---

mozillians/graphql_profiles/schema.py

* Normalize HRIS name attributes.
* Inherit common attributes from BaseGrapheneObject.

Add HRIS data in mozillians.org.

---

mozillians/graphql_profiles/urls.py
mozillians/graphql_profiles/views.py
mozillians/settings.py
mozillians/templates/graphene/graphiql.html

Various fixes for GraphQL

---

docs/installation/installation-docker.rst

Fixes bug id [1495699](https://bugzilla.mozilla.org/show_bug.cgi?id=1495699)

Updated building mozillians using docker doc

---

mozillians/graphql_profiles/decorators.py
mozillians/graphql_profiles/mutation.py
mozillians/graphql_profiles/views.py
mozillians/settings.py

* Resolve csp issues.
* Add anonymous_csrf_exempt

Do not allow anonymous edits.

---

mozillians/dino_park/views.py
mozillians/graphql_profiles/views.py
mozillians/jinja2/dino_park/index.html

* Remove login links from index.html.

Require authentication to access dino-park.

---

k8s/templates/configmap.yml

Reverts mozilla/mozillians#2934

Revert "removes hard-coded namespace in configmap"

---

setup.cfg

Reverts mozilla/mozillians#2936

Revert "Temporarily disable W504 in flake."

---

mozillians/graphql_profiles/resolvers.py
mozillians/graphql_profiles/schema.py

* Reduce nesting fields by moving them top level.

Adapt to the latest v2 Schema.

---

mozillians/graphql_profiles/query.py
mozillians/graphql_profiles/resolvers.py
mozillians/graphql_profiles/schema.py
mozillians/graphql_profiles/utils.py

* Reogranize GraphQL files.
* Create an Abtract V2 Profile.

Move vouches top level.

---

mozillians/dino_park/utils.py
mozillians/dino_park/views.py

Reverts mozilla/mozillians#3070

Revert "Check attribute before retrieving a profile."

---

mozillians/common/authbackend.py
mozillians/common/tests/test_authbackend.py
mozillians/groups/admin.py
mozillians/users/models.py

Always propagate access groups.

---

mozillians/dino_park/views.py

Render 404 page in /beta if not in DinoPark.

---

mozillians/common/authbackend.py
mozillians/common/tests/test_authbackend.py
mozillians/users/signals.py

* Add a logger for group removal signal.

Simplify login for account deracheting.

---

mozillians/common/authbackend.py

Update 2FA error wording.

---

requirements/prod.txt

Reverts mozilla/mozillians#3358

Revert "Update jsonschema to 3.0.0"

---

CODE_OF_CONDUCT.md
README.md

Add Code of Conduct template.
